# Dimensiones

In [5]:
import numpy as np
scalar = np.array(42)
scalar.ndim

0

In [14]:
# 1D
vector = np.array([1,2,3])
vector.ndim

1

In [13]:
# 2D
matriz = np.array([[1,2],[3,4]])
print(matriz)
matriz.ndim

[[1 2]
 [3 4]]


2

In [12]:
# 2D
tensor = np.array([[[1,2,6],[3,4,6],[5,2,3],[1,2,3]],[[1,2,6],[3,4,6],[5,2,3],[1,2,3]]])
print(tensor)
tensor.ndim

[[[1 2 6]
  [3 4 6]
  [5 2 3]
  [1 2 3]]

 [[1 2 6]
  [3 4 6]
  [5 2 3]
  [1 2 3]]]


3

### Agregar dimensiones

In [18]:
vector = np.array([1,2,3], ndmin=10)
print(vector)
vector.ndim

[[[[[[[[[[1 2 3]]]]]]]]]]


10

In [22]:
# Expandir dimensiones
expand = np.expand_dims(np.array([1,2,3]), axis=0)
print(expand)
expand.ndim

[[1 2 3]]


2

In [26]:
# Eliminar dimensiones
print(vector, vector.ndim)
vector_clr = np.squeeze(vector)
print(vector_clr, vector_clr.ndim)

[[[[[[[[[[1 2 3]]]]]]]]]] 10
[1 2 3] 1
