# Creando Arrays

In [1]:
import numpy as np

In [35]:
# range
np.arange(0,10)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
# range
np.arange(0,20,2)


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [33]:
# Zeros
np.zeros(3)

array([0., 0., 0.])

In [31]:
# Zeros
np.zeros((10,10))


array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [30]:
# Ones
np.ones((10,5))


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [28]:
# Desde Hasta Cuantos
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [29]:
# Matriz diagonal
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [45]:
# random
np.random.rand()

0.34198709599119237

In [44]:
# random vector
np.random.rand(4)

array([0.82041694, 0.14605399, 0.77178078, 0.24514233])

In [47]:
# random matriz
np.random.rand(4,4)

array([[0.98344427, 0.73056539, 0.18023126, 0.29866656],
       [0.61528126, 0.60110116, 0.67825204, 0.83425157],
       [0.10213838, 0.81197696, 0.83329492, 0.25239849],
       [0.25767269, 0.14636547, 0.1687148 , 0.31042241]])

In [55]:
# rand int
np.random.randint(1,15)

13

In [57]:
# rand int matriz
np.random.randint(1,100,(10,10))

array([[82, 26, 27, 27, 83, 89, 12, 79, 80, 93],
       [ 6,  9, 31, 79, 53, 48, 84, 94, 56, 77],
       [ 6, 62, 51, 85, 55, 74, 71, 37, 95, 48],
       [83, 10, 69, 25,  1, 27, 74, 85, 46, 14],
       [95, 27, 97, 31, 88, 57,  8, 64, 42, 45],
       [92, 84, 57, 91, 43, 10, 44, 54, 34, 34],
       [64, 36, 10, 85, 58, 79, 46, 32, 83, 32],
       [52, 98, 14, 40, 56, 66, 31, 19, 97, 59],
       [75,  3, 62, 82, 45, 68, 52, 39, 59, 71],
       [47, 63, 46, 19, 64, 69, 69, 35, 24, 28]])