# Funciones Principales

In [1]:
import numpy as np

In [6]:
arr = np.random.randint(1,20,10)
arr

array([17, 12, 17, 12,  6,  7, 12,  8, 16,  3])

In [11]:
matriz = arr.reshape(2,5)
matriz

array([[17, 12, 17, 12,  6],
       [ 7, 12,  8, 16,  3]])

In [49]:
print("Valore max ",matriz.max())

# Sacar maximo por filas
print("Max por filas ",matriz.max(1))

# Sacar maximo por columnas
print("Max por columnas ", matriz.max(0))

# indica el indice del valor maximo
print("indice valor max matriz ", matriz.argmax())

# indica el indice del valor maximo
print("Indice valor max",arr.argmax())

Valore max  17
Max por filas  [17 16]
Max por columnas  [17 12 17 16  6]
indice valor max matriz  0
Indice valor max 0


## Valores Menores

In [50]:
print("Valor menor", arr.min())

Valor menor 3


In [53]:
print("Valor menor matriz", matriz.min())
print("Indice valor menor", arr.argmin())
print("Indice valor menor matriz", matriz.argmin())


Valor menor matriz 3
Indice valor menor 9
Indice valor menor matriz 9


# Direfencia entre pico mas alto y el mas bajo

In [54]:
print(arr)
print("ptp arr", arr.ptp())

[17 12 17 12  6  7 12  8 16  3]
ptp arr 14


In [57]:
print(matriz)
print("ptp matriz", matriz.ptp())
# ptp en matriz en columnas
print("ptp matriz columna", matriz.ptp(0))
# ptp en matriz en filas
print("ptp matriz filas", matriz.ptp(1))


[[17 12 17 12  6]
 [ 7 12  8 16  3]]
ptp matriz 14
ptp matriz columna [10  0  9  4  3]
ptp matriz filas [11 13]


## Percentil

In [65]:
print(arr)
print("Percentil valor alto ",np.percentile(arr, 100))
print("Percentil valor mitad ",np.percentile(arr, 50))
print("Percentil valor bajo ",np.percentile(arr, 0))

[ 3  6  7  8 12 12 12 16 17 17]
Percentil valor alto  17.0
Percentil valor mitad  12.0
Percentil valor bajo  3.0


In [66]:
print("Ordena el codigo ", arr.sort())

None


## Mediana

In [70]:
print(arr)
print("mediana de arr" ,np.median(arr))
print(matriz)
print("mediana de matriz por columna" ,np.median(matriz, 0))
print("mediana de matriz por fila" ,np.median(matriz, 1))

[ 3  6  7  8 12 12 12 16 17 17]
mediana de arr 12.0
[[ 3  6  7  8 12]
 [12 12 16 17 17]]
mediana de matriz por columna [ 7.5  9.  11.5 12.5 14.5]
mediana de matriz por fila [ 7. 16.]


## Desviacion estandar

In [77]:
print("Desv Est arr",np.std(arr))
print("varianza",np.std(arr)**2)

Desv Est arr 4.626013402488151
varianza 21.4


# Varianza

In [76]:
print("Varianza arr",np.var(arr))

Varianza arr 21.4


# Media

In [79]:
print(np.mean(arr))

11.0


## Concatenar

In [87]:
a = np.random.randint(1,10, (2,2))
print("array a \n",a)
b = np.random.randint(1,10, (2,2))
print("array b \n",b)
print("Concatenate\n", np.concatenate((a,b), axis=0))

array a 
 [[8 4]
 [3 2]]
array b 
 [[1 6]
 [1 1]]
Concatenate
 [[8 4]
 [3 2]
 [1 6]
 [1 1]]
