# Tipos de datos

In [1]:
import numpy as np

arr = np.array([1,2,3,4])
arr.dtype

dtype('int64')

In [2]:
arr = np.array([1,2,3,4], dtype="float64")
arr.dtype

dtype('float64')

In [3]:
arr

array([1., 2., 3., 4.])

In [4]:
# Conversion
arr = np.array([1,2,3,4])
arr_fl64 = arr.astype(np.float64)
arr_fl64

array([1., 2., 3., 4.])

In [14]:
# Conversion boolean
arr_bool = arr.astype(np.bool_)
arr_bool

array([ True,  True,  True,  True])

In [15]:
# Conversion String
arr_str = arr.astype(np.string_)
arr_str

array([b'1', b'2', b'3', b'4'], dtype='|S21')

In [16]:
# Conversion Integer
arr_str = np.array(["1","2","3","4"])
arr = arr_str.astype(np.int8)
arr

array([1, 2, 3, 4], dtype=int8)