# Creando Arrays

In [3]:
import numpy as np

In [35]:
# range
np.arange(0,10)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
# range
np.arange(0,20,2)


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [33]:
# Zeros
np.zeros(3)

array([0., 0., 0.])

In [31]:
# Zeros
np.zeros((10,10))


array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [1]:
# Ones
np.ones((10,5))


NameError: name 'np' is not defined

In [4]:
# Desde Hasta Cuantos
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [5]:
# Matriz diagonal
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [8]:
# random
np.random.rand()

0.8383225075388322

In [10]:
# random vector
np.random.rand(4)

array([0.94792717, 0.40734245, 0.5333278 , 0.52265887])

In [11]:
# random matriz
np.random.rand(4,4)

array([[0.52841835, 0.78369244, 0.04903241, 0.907164  ],
       [0.05165986, 0.80971863, 0.20334604, 0.46492778],
       [0.68208256, 0.38738565, 0.14864396, 0.67448916],
       [0.6096003 , 0.73209975, 0.15379366, 0.30549356]])

In [12]:
# rand int
np.random.randint(1,15)

12

In [13]:
# rand int matriz
np.random.randint(1,100,(10,10))

array([[68, 72, 77,  9, 81, 88,  2, 23, 92, 94],
       [ 9, 83, 64, 42, 38,  9, 14, 56, 55, 50],
       [ 2,  7, 72, 97, 61, 14, 45, 23, 74, 34],
       [55, 61, 15, 29, 74, 72, 13, 68, 84, 96],
       [72, 90, 13, 84, 98, 26, 79, 73, 54, 72],
       [42, 38, 83, 75, 54, 55, 29, 43, 20, 66],
       [67, 95, 11, 64, 91, 85, 35, 73, 12, 19],
       [ 8, 59, 49, 34, 26, 10, 92, 87, 62, 65],
       [65, 89, 50, 67, 30, 62, 24, 41, 38, 39],
       [ 2, 70,  7, 17, 26, 59, 16, 82,  2,  1]])