In [ ]:
# Shape y reshape

In [2]:
import numpy as np


In [11]:
arr = np.random.randint(1,10,(3,2))
arr

array([[6, 1],
       [7, 2],
       [1, 5]])

In [8]:
arr.shape  # Give the shape 

(3, 2)

In [16]:
arr.reshape(1,6)

array([[6, 1, 7, 2, 1, 5]])

In [18]:
arr.reshape(2,3)

array([[6, 1, 7],
       [2, 1, 5]])

In [20]:
arr

array([[6, 1],
       [7, 2],
       [1, 5]])

In [21]:
# Ordenar por lenguaje de programacion
np.reshape(arr,(2,3),'C') # Lenguaje C

array([[6, 1, 7],
       [2, 1, 5]])

In [23]:
np.reshape(arr, (2,3), 'F') # Lenguaje F

array([[6, 1, 2],
       [7, 1, 5]])

In [25]:
 np.reshape(arr, (2,3),'A')  # Por el tipo de guardado de datos en el sistema, En este caso es del tipo 'C'

array([[6, 1, 7],
       [2, 1, 5]])