# Condiciones

In [2]:
import numpy as np

In [11]:
arr = np.linspace(1,10,10, dtype='float')
print(arr)
indice_mayor = arr>5
print("Valor mayores:", indice_mayor)
print("Mostrar valores mayores",arr[indice_mayor])

indice_menor = arr<5
print(f"Valor menores: {indice_menor}")
print(f"Mostrar valores menores {arr[indice_menor]}", end="\n"*3)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
Valor mayores: [False False False False False  True  True  True  True  True]
Mostrar valores mayores [ 6.  7.  8.  9. 10.]
Valor menores: [ True  True  True  True False False False False False False]
Mostrar valores menores [1. 2. 3. 4.]




## And y Or

In [18]:
print(f"And {arr[(arr>2) & (arr<7)]}")
arr[arr>6] = 100
print(f"Valores cambiados {arr}")
print(f"Igual igual {arr[arr==100]}")

And [3. 4. 5. 6.]
Valores cambiados [  1.   2.   3.   4.   5.   6. 100. 100. 100. 100.]
Igual igual [100. 100. 100. 100.]


## Where

In [22]:
matriz = np.random.randint(1,100, (3,5))
print(matriz)
print("where(condicion, valor si cumple, si no cumple)")
print(np.where(matriz>50,0,1))


[[ 9 62 20 80 11]
 [86 10 37  4 55]
 [88 13 45 81 73]]
where(condicion, valor si cumple, si no cumple)
[[1 0 1 0 1]
 [0 1 1 1 0]
 [0 1 1 0 0]]


In [31]:
a = np.linspace(1,100,20,dtype="float")
a[(a<50)]

array([ 1.        ,  6.21052632, 11.42105263, 16.63157895, 21.84210526,
       27.05263158, 32.26315789, 37.47368421, 42.68421053, 47.89473684])